services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atlas_db
    ports:
      - "3306:3306"
    volumes:
      - atlas_data:/var/lib/mysql
  backend:
    build: ./server
    ports:
      - "3310:3310"
    volumes:
      - ./server:/api
      - /api/node_modules
    environment:
      APP_PORT: 3310
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: atlas_db
      CLIENT_URL: http://localhost:3000
    depends_on:
      - database

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:3310
    depends_on:
      - backend

volumes:
  atlas_data: