FROM node:20-alpine AS build

WORKDIR /api

COPY package.json package.json

RUN npm install

COPY . .

RUN npm run build

FROM node:20-alpine

WORKDIR /api

COPY package.json package.json

RUN npm install

COPY --from=build /api/dist ./dist

EXPOSE 3310

CMD [ "node", "dist/src/main.js" ]